service: vacgom-image-gen
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: 'ap-northeast-1'

functions:
  hello:
    handler: handler.generate
    layers:
      - arn:aws:lambda:ap-northeast-1:205979422636:layer:napi-rs-canvas:886
    events:
      - httpApi:
          path: /
          method: get


plugins:
  - serverless-plugin-typescript
package:
  patterns:
    - assets/*.otf
